### PR TITLE
Added error handling to make it more clear why things go wrong.

### PR DESCRIPTION
**Pull request by perlun**
Thanks for a nice project! We are currently using Mizuno a lot in production, but I decided to look into Fishwife as an option going forward.

I realized this could be added while trying to set this project up tonight; `bundle install` didn't do what you'd expect in this project so therefore I added some details about it here.

(Maybe it's the `rake install` that would be the proper way to bootstrap stuff instead. Then we could perhaps add a `Hacking/Developing` section in the README about it instead. As a new person, with a lot of experience with Ruby but none whatsoever with the `jrack-tarpit` approach, it felt unintuitive to just not be able to `bundle install` my way off.)

Suggestions/improvements to this is of course welcome.

### CODE REVIEW

**Comment by dekellum** [comment]
Hi @perlun, I can understand your initial surprise and I'm glad to see you were able to figure out the dependency as listed in the gemspec source (`gem` line) and spec output.  Yes rjack-tarpit needs to be installed for development first, just like bundler needs to be installed, and for that matter jruby and the JDK. As I was concerned that a later version of bundler might be masking the error, I uninstalled rjack-tarpit to test the original, which I find is as below:

```
[!] There was an error parsing `Gemfile`: There was a Gem::LoadError while loading fishwife.gemspec: 
Could not find 'rjack-tarpit' (~> 2.1) among 82 total gem(s)
```

Were you seeing something else, less descriptive?

I ask because I think the above error is reasonably clear and sufficient for a development-specific setup. Also this is the same gemspec format as used by some 65 public gems. There is nothing special about fishwife's particular use of rjack-tarpit, that would warrant this extra attempt at error handling.

**Comment by perlun** [comment]
> Were you seeing something else, less descriptive?

No, you're right - it was similar to what I saw.

I think my main confusion stems from the fact that the project had a somewhat "odd", non-standard way of being bootstrapped. Normally, Ruby gems can be bootstrapped using a simple `git clone foo && cd clone && bundle install` approach. As a Ruby developer, that's what I expect when I look at (to me) new project, and since that wasn't the case here I looked into making it more intuitive. But you're right, my attempt perhaps doesn't solve it all.

What I'd like:
- If the user types `bundle install` without `rjack-tarpit` being installed (using `gem install`), give the user a reasonably friendly error message informing them on how to proceed. This is what I tried with my approach.

The message we produce right now gives a _hint_ on how to solve the problem, but it doesn't give the full solution (like my patch tries to do). `Could not find 'jrack-tarpit' among 82 total gem(s)`. What are those gems? Is it the gems that this project depends on? Is it the gems I have installed in my Ruby? (the latter is true, but it's easy to misunderstand)

Just my 0.02€. I _know_ that some of my colleagues would be confused by seeing that message that we currently produce; I was confused myself. If you don't want to add this, then I think we should add a `Contributing` text in the `README.rdoc` file explaining how to bootstrap stuff.

**Comment by dekellum** [comment]
One definition of "normal" might be, like Mizuno, to avoid issues of java build integration and dependencies by checking jars into git.  I prefer to keep fishwife "odd" by such a comparison, and I don't think the current error message is so obscure as to justify the eﬀort for fishwife and the 64 other public gems using this tooling.  Thanks for your input.

**Comment by perlun** [comment]
> One definition of "normal" might be, like Mizuno, to avoid issues of java build integration and dependencies by checking jars into git.

Don't get me wrong man - I think it's nice that Fishwife has chosen a different approach, _depending_ on `rjack-jetty` instead of embedding the JARs (like Mizuno has done). And even `jrack-jetty` probably don't embed the JARs either, but instead pulls them down using Maven.

I think that's good.

> I prefer to keep fishwife "odd" by such a comparison, and I don't think the current error message is so obscure as to justify the eﬀort for fishwife and the 64 other public gems using this tooling. Thanks for your input.

Sorry if "odd" is a bad wording in this case (I'm not a native English speaker). To me, not having used any `jrack-*` project whatsoever, but having years of Ruby experience, it felt different (which it is! for good reasons).

All I want is for people to have an easy way to find this. Would you mind if I submit a `Contributing to the project` part for the README? I can do it, but only if you are interested in it (don't want to waste time submitting stuff that will get rejected. :smile:)

All in all, thanks for a nice project. Mizuno seems, sadly, a bit dead at the moment, so I consider Fishwife the "spiritual successor" to it.

**Comment by dekellum** [comment]
I've added a section to README in e1388dd.  I'll consider refinements to that section if you think its incomplete.

**Pull request closed without merging**
